kind: pipeline
name: default

steps:
- name: mariadb
  image: mariadb
  commands:
  - sleep 15
  - mysql -u root -h database --execute="SELECT VERSION();"

- name: composer
  image: composer
  commands:
  - composer -V
  - composer install --prefer-dist

- name: php
  image: php:fpm-alpine
  commands:
  - php -v
  - cp .env.example .env
  - php artisan key:generate
  - docker-php-ext-install pdo pdo_mysql
  - php artisan migrate
  - php artisan db:seed

- name: node
  image: node
  commands:
  - node -v
  - npm -v
  - npm install
  - npm run production

- name: nginx
  image: nginx
  commands:
  - nginx -v

services:
- name: database
  image: mariadb
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: ${DB_DATABASE}
  