kind: pipeline
name: default

steps:
- name: mariadb
  image: mariadb
  commands:
  - sleep 15
  - mysql -u root -h database --execute="SELECT VERSION();"

- name: composer
  image: composer
  commands:
  - composer -V
  - composer install --prefer-dist

- name: php
  image: php:fpm-alpine
  commands:
  - php -v
  - cp .env.example .env
  - php artisan key:generate
  - docker-php-ext-install pdo pdo_mysql
  - php artisan migrate
  - php artisan db:seed

- name: node
  image: node
  commands:
  - node -v
  - npm -v
  - npm install
  - npm run production

- name: nginx
  image: nginx
  commands:
  - nginx -v

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    channel:
      from_secret: SLACK_CHANNEL

- name: line
  image: appleboy/drone-line
  environment:
    LINE_CHANNEL_SECRET:
        from_secret: LINE_CHANNEL_SECRET
    LINE_CHANNEL_TOKEN:
        from_secret: LINE_CHANNEL_TOKEN
    PLUGIN_TO_GROUP:
        from_secret: PLUGIN_TO_GROUP
    PLUGIN_MESSAGE: |
      test success
      ${DRONE_REPO}
      ${DRONE_COMMIT_BRANCH}
      ${DRONE_COMMIT_SHA}
      ${DRONE_COMMIT_MESSAGE}

services:
- name: database
  image: mariadb
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: ${DB_DATABASE}
  