version: "3"
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DOCKER_PATH}/mariadb/data:/var/lib/mysql
      - ${DOCKER_PATH}/mariadb/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  php:
    build:
      context: ${DOCKER_PATH}/php
    volumes:
      - ${DOCKER_PATH}/php/php.ini:/usr/local/etc/php/php.ini
      - ${DOCKER_PATH}/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:rw
      - ${DOCKER_PATH}/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${DOCKER_PATH}/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ${DOCKER_PATH}/php/log/:/var/log/php/:rw
      - ${DOCKER_PATH}/php/sock:/sock
      - ${LARAVEL_PATH}/:/usr/share/nginx/html/laravel
    ports:
      - "9000:9000"
  nginx:
    image: nginx:latest
    volumes:
      - ${DOCKER_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DOCKER_PATH}/nginx/conf.d:/etc/nginx/conf.d
      - ${DOCKER_PATH}/nginx/log:/var/log/nginx
      - ${DOCKER_PATH}/php/sock:/sock
      - ${LARAVEL_PATH}/:/usr/share/nginx/html/laravel
    ports:
      - "80:80"
      - "443:443"

